"""empty message

Revision ID: users_removeemail_addad
Revises: users
Create Date: 2025-11-12 16:53:13.445328

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "users_removeemail_addad"
down_revision: Union[str, Sequence[str], None] = "users"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("from_ad", sa.Boolean(), nullable=True))
    # 2. Define valor padrão para registros existentes
    op.execute("UPDATE users SET from_ad = FALSE")

    op.alter_column("users", "from_ad", existing_type=sa.Boolean(), nullable=False)

    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(None, "users", ["id"])
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "from_ad")
    # ### end Alembic commands ###
